### ISSUE TITLE
failure on osx

### ISSUE THREAD

**Issue by querry43** [eikenb/aws-console#1]
````
$ python2.7 ./aws-console 

Traceback (most recent call last):
  File "./aws-console", line 181, in <module>
    if getArgs().create_role:
  File "./aws-console", line 56, in getArgs
    cache.append(parseArgs())
  File "./aws-console", line 34, in parseArgs
    browser_name = webbrowser.get().name
AttributeError: 'MacOSXOSAScript' object has no attribute 'name'
````

**Comment by jorgedlt** [comment]
I too am having this issue, previously everything was working. I reinstalled MACOSX with 10.12.6- now I get the same exact we above
